### ISSUE TITLE
Argument for "Action"?

### ISSUE THREAD

**Issue by speckenbuettel** [mqtt-home/fritzbox-to-mqtt-gw#86]
Hi!

Is it possible to define an argument for an action?

For example, if I want to know the details of a specific host, I would use the service "serviceId:Hosts1" and the action "GetSpecificHostEntry", but then I would need to provide the mac address as argument for the action:

![image](https://github.com/user-attachments/assets/1f46b607-744e-4eff-9f0b-5812e5d212f3)

Thank you.

**Comment by philipparndt** [comment]
Hi @speckenbuettel thanks for the idea, this is available in v5.1.0

```json
{
    "service": "urn:dslforum-org:service:Hosts:1",
    "action": "GetSpecificHostEntry",
    "args": [
        { "name": "NewMACAddress", "value": "12:34:56:78:9A:BC" }
    ],
    "alias": "host1"
},
```
